language: node_js
node_js:
  - '7'
git:
  depth: 5
branches:
  only:
  - master
  - /^(\d+\.){2}\d+$/
# after_success: npm run cover
# before_deploy: npm run prepare-github-pages
deploy:
  # - provider: pages
  #   skip-cleanup: true
  #   github-token: $GITHUB_TOKEN
  #   keep-history: true
  #   local-dir: docs
  #   on:
  #     branch: master
  - provider: script
    skip-cleanup: true
    script: npm run npm:publish
    on:
      tags: true